POST http://localhost:3001/cart
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYxOTUwMTNlMzE4MWU4MzlkMmU3NmNmZSIsImlhdCI6MTYzNzE1NTI5NywiZXhwIjoxNjM3MTU3MDk3fQ.kUJCRHx3acik-wYS5spqBr6rcQ1yWwWxb6Yih8TmliU

{
    "product": "6195011c8c79877ffc4d4768",
    "quantity": "1"   
}

###
POST http://localhost:3001/cart
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYxOTUwMTNlMzE4MWU4MzlkMmU3NmNmZSIsImlhdCI6MTYzNzE1NTI5NywiZXhwIjoxNjM3MTU3MDk3fQ.kUJCRHx3acik-wYS5spqBr6rcQ1yWwWxb6Yih8TmliU

{
    "product": "6195011c8c79877ffc4d4764",
    "quantity": "1"   
}

###
DELETE http://localhost:3001/cart/6195011c8c79877ffc4d4764
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYxOTUwMTNlMzE4MWU4MzlkMmU3NmNmZSIsImlhdCI6MTYzNzE1NTI5NywiZXhwIjoxNjM3MTU3MDk3fQ.kUJCRHx3acik-wYS5spqBr6rcQ1yWwWxb6Yih8TmliU

###
DELETE http://localhost:3001/cart/6171538fd86559773e15175c
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYxOTUwMTNlMzE4MWU4MzlkMmU3NmNmZSIsImlhdCI6MTYzNzE1NTI5NywiZXhwIjoxNjM3MTU3MDk3fQ.kUJCRHx3acik-wYS5spqBr6rcQ1yWwWxb6Yih8TmliU

###
GET http://localhost:3001/cart
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYxOTUwMTNlMzE4MWU4MzlkMmU3NmNmZSIsImlhdCI6MTYzNzE1NTY3MiwiZXhwIjoxNjM3MTU3NDcyfQ.8DtsszjlEhbcl2FuW_TZGdZrmqDYq7gmEFH-g1tRFFk
